export const ADD_TO_CHECKOUT = 'ADD_TO_CHECKOUT';
export const ADD_TO_CHECKOUT_ERROR = 'ADD_TO_CHECKOUT_ERROR';
export const REMOVE_FROM_CHECKOUT = 'REMOVE_FROM_CHECKOUT';
export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY';
export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY';
export const UPDATE_ALL_ITEM_COSTS = 'UPDATE_ALL_ITEM_COSTS';
export const SET_DELIVERY_ADDRESS = 'SET_DELIVERY_ADDRESS'; 
